config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  authenticate :user, ->(u) { u.effective_admin? } do
    mount Sidekiq::Web => '/admin/sidekiq'
  end

  scope path_names: { sign_in: 'login', sign_out: 'logout' } do
    devise_for :user, controllers: { sessions: 'devise/user/sessions' }
    devise_for :subscriber_user, controllers: { passwords: 'devise/subscriber/passwords' }
  end

  resource :admin, only: :show

  namespace :admin do
    get 'welcome', to: 'welcome#index'
    get 'toggle_become_admin', to: 'welcome#toggle_become_admin'
    scope except: :show do
      resources :sms_lists do
        member do
          get :export
        end
      end
      resources :subscribers do
        collection do
          get :sms_operator
        end
        resources :email_problems, except: %i[show destroy]
        resources :phone_problems, except: %i[show destroy]
        resources :subscriber_statistics, only: :index
      end
      resources :import_email_problems, only: %i[new create]
      resources :import_phone_problems, only: %i[new create]
      resources :time_zones
      resources :smtp_setting_groups do
        collection { post :sort }
        resources :smtp_settings
      end
      resources :unsubscription_reasons do
        collection { post :sort }
      end
      resources :email_problem_names do
        collection { post :sort }
      end
      resources :phone_problem_names do
        collection { post :sort }
      end
      resources :digest_categories
      resources :news_items
      resources :settings, only: %i[index show edit update]
      resources :sms_operators do
        collection do
          get :export
        end
      end
      resources :messenger_types
      resources :phone_prefixes
      resources :blacklist_emails
      resources :banner_owners
      resources :external_redirects
      resources :polls do
        resources :answers
        resources :subscriber_answers, only: :index
      end
      resources :pages
      resources :stripo_template_groups do
        resources :stripo_templates do
          member do
            get :edit_stripo
          end
        end
      end
      resources :stripo_templates, only: [] do
        collection do
          get :new_from_mailing, to: 'stripo_templates#new_from_mailing'
          post :new_from_mailing, to: 'stripo_templates#create_from_mailing'
        end
      end
      resources :api_keys
      resources :donation_methods
      resources :mailing_requests do
        resources :mailing_request_messages, only: %i[index create]
      end
      resources :mailing_destinations
    end
    resources :email_lists do
      resources :email_list_custom_vars
      resources :email_list_var_names do
        collection { post :sort }
      end
      member do
        get :export
      end
    end
    resources :email_digests do
      member do
        put :send_digest
        put :cancel_sending
      end
    end
    resources :unsubscriptions, only: %i[index show destroy]
    resources :users
    resources :mailings do
      member do
        get :full
        get :frame
        put :copy
        put :send_mailing
        put :cancel_sending
        get :crop
      end
      resources :mailing_statistics, only: :index
    end
    resources :sms_sendings do
      collection do
        put :multiple
      end
      member do
        put :copy
        put :send_sms
        put :cancel_sending
      end
    end
    resources :telegram_groups
    resources :telegram_messages do
      collection do
        get :recent_mailings
      end
      member do
        put :copy
        put :send_message
        put :cancel_sending
      end
    end
    resources :cities
    resources :sms_messages, only: %i[index edit update]
    resources :sms_send_history_types, only: %i[index edit update]
    resources :email_send_histories, only: %i[index destroy]
    resources :sms_send_histories, only: %i[index destroy]
    resources :sms_accounts do
      resources :sms_account_actions, except: :destroy
    end
    resources :banner_orders, except: :show do
      resources :banners
    end
    resources :subscriber_imports, except: :show do
      resources :subscriber_import_people, only: %i[index edit update]
    end
    resources :text_blocks, only: %i[index edit update]
    resources :surveys do
      resources :survey_questions do
        resources :survey_answers
        resources :survey_subscriber_answers, only: %i[index show]
      end
    end

    wiki_root '/wiki'
  end

  namespace :api do
    namespace :mobile do
      resources :token, only: %i[create destroy] do
        member do
          get :validate
        end
      end
      resources :email_lists, only: :index do
        resources :mailings, only: %i[index show]
      end
      resource :registration, only: %i[show create update destroy]
      namespace :v2 do
        resources :email_lists, only: :index do
          resources :mailings, only: :index
        end
      end
      resources :time_zones, only: :index
      resources :search_mailings, only: :index
    end
    namespace :stripo do
      scope :files do
        get '/', to: 'files#list'
        get 'info', to: 'files#info'
        post '/', to: 'files#upload'
        post 'delete', to: 'files#delete'
      end
      get 'token', to: 'auth#token'
    end
  end

  resource :registration, only: %i[new create edit update destroy]
  resource :email_confirmations, only: %i[show] do
    collection do
      get :confirm
    end
  end
  resources :email_lists, only: %i[index show] do
    resources :mailings, only: :index
  end
  resources :facebook_groups, only: :index
  resources :telegram_groups, only: :index
  resources :viber_groups, only: :index
  resources :vk_groups, only: :index
  resources :whatsapp_groups, only: :index
  resources :mailings, only: :show do
    member do
      get :full
      get :track_email
    end
  end
  resource :my_settings, only: %i[edit update] do
    collection do
      get :time_zone
    end
  end
  resources :pages
  resource :contact, only: %i[new create]
  resources :unsubscriptions, only: %i[new create]
  resources :news_items, only: %i[index show], path: 'news'
  resources :subscriber_answers, only: :new
  resources :search_mailings, only: %i[index]
  resources :survey_subscriber_answers, only: %i[edit update]
  resources :mailing_requests, except: :show do
    resources :mailing_request_messages, only: %i[index create]
  end

  get 'banner_click' => 'banner_clicks#new'
  post 'phones_prolong/create'

  root to: 'pages#index'
end

app/models/mailing_request.rb
# frozen_string_literal: true

class MailingRequest < ApplicationRecord
  MAILING_STATUSES = { awaiting_admin_response: 1, awaiting_subscriber_response: 2, awaiting_donation: 3,
                       processed: 4 }.freeze
  MAILING_TYPES = { private: 1, commercial: 2 }.freeze

  has_many :images, class_name: 'MailingRequestImage', dependent: :destroy
  has_many :messages, class_name: 'MailingRequestMessage', dependent: :delete_all
  belongs_to :donation_method, optional: true
  belongs_to :subscriber
  has_and_belongs_to_many :email_lists
  belongs_to :mailing, optional: true

  scope :ordered, -> { order(created_at: :desc) }
  scope :authorized, ->(subscriber) { where(subscriber:) }

  validates :subject, :body, :mailing_type, presence: true

  accepts_nested_attributes_for :images, allow_destroy: true, reject_if: :all_blank

  enum :status, MAILING_STATUSES, suffix: true
  enum :mailing_type, MAILING_TYPES, suffix: true
end

app/controllers/admin/mailing_requests_controller.rb
# frozen_string_literal: true

module Admin
  class MailingRequestsController < BaseController
    include CollectionLoaders

    before_action :set_mailing_request, only: %i[edit update destroy]
    before_action :set_mailing_types, only: %i[edit update]
    before_action :set_mailing_request_statuses, only: %i[edit update]
    before_action :set_email_lists_for_mailing_requests, only: %i[edit update]

    def index
      @mailing_requests = authorize policy_scope(MailingRequest).ordered
    end

    def edit; end

    def update
      if @mailing_request.update(permitted_attributes(@mailing_request))
        redirect_to admin_mailing_requests_url, notice: t('flash.mailing_request.update')
      else
        render :edit
      end
    end

    def destroy
      @mailing_request.destroy
      redirect_to admin_mailing_requests_url, notice: t('flash.mailing_request.destroy')
    end

    private

    def set_mailing_request
      @mailing_request = authorize MailingRequest.find(params[:id])
    end
  end
end

app/controllers/mailing_requests_controller.rb
# frozen_string_literal: true

class MailingRequestsController < ApplicationController
  include CollectionLoaders

  before_action :set_mailing_request, only: %i[edit update destroy]
  before_action :set_mailing_types, only: %i[new create edit update]
  before_action :set_email_lists_for_mailing_requests, only: %i[new create edit update]
  before_action :set_mailing_request_statuses, only: %i[new create edit update]

  def index
    @mailing_requests = authorize policy_scope(MailingRequest).ordered
  end

  def new
    @mailing_request = authorize MailingRequest.new
  end

  def edit; end

  def create
    @mailing_request = authorize MailingRequest.new(permitted_attributes(MailingRequest.new))
    @mailing_request.status = :awaiting_admin_response
    @mailing_request.subscriber_id = current_subscriber_user.id
    if @mailing_request.save
      MailingRequest::NotifyNewMailingRequest.call(@mailing_request)
      redirect_to mailing_requests_url, notice: t('flash.mailing_request.create')
    else
      render :new
    end
  end

  def update
    if @mailing_request.update(permitted_attributes(@mailing_request))
      redirect_to mailing_requests_url, notice: t('flash.mailing_request.update')
    else
      render :edit
    end
  end

  def destroy
    @mailing_request.destroy
    redirect_to mailing_requests_url, notice: t('flash.mailing_request.destroy')
  end

  private

  def set_mailing_request
    @mailing_request = authorize MailingRequest.find(params[:id])
  end
end

app/views/mailing_requests/_form.html.haml
= link_to_back mailing_requests_path

= form_wrapper t("actions.mailing_request.#{action}") do
  = simple_nested_form_for @mailing_request, html: { multipart: true } do |f|
    = error_notifications(f)

    = fieldset do
      - unless @mailing_request.awaiting_donation_status?
        = f.input :subject
        = f.input :body
        = f.association :email_lists, as: :check_boxes, collection: @email_lists
        = f.input :deliver_at
        %p
          У нас есть правила, которые разделяют коммерческие рассылки от частных. Если в рассылках есть ассортимент и
          указан прайс лист, или платные семинары и курсы, то это коммерческая рассылка и у нее есть стоимость 1000
          рублей. Частные рассылки мы рассылаем за свободное пожертвование.
        = f.input :mailing_type, collection: @mailing_types
        = f.simple_fields_for :images do |builder|
          = render 'images', f: builder
        = f.link_to_add 'Добавить фотографию', :images
      = f.association :donation_method
      = f.input :donated_at
      = f.input :comments
    = f.button :submit

app/views/mailing_requests/_images.html.haml
.input-group
  = f.input :image, as: :hidden, input_html: { value: f.object.cached_image_data }
  - if f.object.image
    = render partial: 'image_preview', locals: { caption: f.object.image.metadata['filename'], image_url: f.object.image_url }
  = f.input :image, label: false
  %span.input-group-addon= f.link_to_remove admin_icon(:destroy)

app/views/mailing_requests/_summary.html.haml
= p_strong t('activerecord.attributes.mailing_request.subject'), @mailing_request.subject
= p_strong t('activerecord.attributes.mailing_request.body'), @mailing_request.body
= p_strong t('activerecord.attributes.mailing_request.email_lists') do
  %ul
    - @mailing_request.email_lists.each do |email_list|
      %li= email_list.name
= p_strong t('activerecord.attributes.mailing_request.deliver_at'), @mailing_request.deliver_at
= p_strong t('activerecord.attributes.mailing_request.mailing_type'), t("mailing_types.#{@mailing_request.mailing_type}")
= p_strong t('activerecord.attributes.mailing_request.donation_method'), @mailing_request.donation_method&.name
= p_strong t('activerecord.attributes.mailing_request.donated_at'), @mailing_request.donated_at
= p_strong t('activerecord.attributes.mailing_request.comments'), @mailing_request.comments

app/views/mailing_requests/edit.html.haml
= render 'form', action: 'edit'

app/views/mailing_requests/index.html.haml
- title t('headers.mailing_requests')

%p= subscriber_link_to_new :mailing_request

.clearfix
.table-responsive
  %table{ class: table_class }
    %thead
      %tr
        %th= t('activerecord.attributes.mailing_request.subject')
        %th= t('activerecord.attributes.mailing_request.status')
        %th.btn-col
        %th.btn-col

    %tbody
      - @mailing_requests.each do |mailing_request|
        %tr
          %td= link_to mailing_request.subject, mailing_request_mailing_request_messages_path(mailing_request)
          %td= t("mailing_request_statuses.#{mailing_request.status}")
          %td.btn-col
            - if policy(mailing_request).edit?
              = link_to_edit mailing_request
          %td.btn-col
            - if policy(mailing_request).destroy?
              = link_to_destroy mailing_request

app/views/mailing_requests/new.html.haml
= render 'form', action: 'create'